using UnityEngine;
using System.Collections.Generic;

public class EventTest : MonoBehaviour
{
    private void Awake()
    {
        Debug.Log("ğŸ‰ğŸ‰WELCOME! Awake ì‹¤í–‰ |ãƒ½(*ï¿£â–½ï¿£*)ãƒãƒŸ|ğŸ‰ğŸ‰");
    }
    

    //Onenableì€ 1íšŒì‹¤í–‰
    private void OnEnable()
    {
        Debug.Log("OnEnable ì‹¤í–‰ ë‚œ ë”± í•œë²ˆë§Œ ë‚˜ì˜¬êº¼ì•¼");
    }

    private void Start()
    {
        Debug.Log("Start! ğŸ’•");
    }
    //FixedUpdateì—ì„œë¶€í„° OnApplicationQuitê¹Œì§€ ê°€ê³  í•œë°”í€´ ë‹¤ì‹œ ëŒì•„ì˜¬ë•Œ í•œ í”„ë ˆì„ ìˆœí™˜í–ˆë‹¤í•¨.
    //FixedUpdateëŠ” 1ì´ˆì— 50í”„ë ˆì„ ê³ ì •
    private void FixedUpdate()
    {
        Debug.Log("FixedUpdateê°€ ë˜ ë‚˜ì˜¤ê²Œ ë˜ğŸ˜«");
    }

    //UpdateëŠ” ë§¤ í”„ë ˆì„ë§ˆë‹¤ í˜¸ì¶œ
    private void Update()
    {
        Debug.Log("ì•™ Updateì‹¤í–‰ë  â˜†*: .ï½¡. o(â‰§â–½â‰¦)o .ï½¡.:*â˜†");
    }

    private void LateUpdate()
    {
        Debug.Log("LateUpdate ë”°ë¼ì™€ë˜ ğŸ¥º ");
    }

    //Disableì€ ë¹„í™œì„±í™”í• ë•Œ ë”± í•œë²ˆ ì‹¤í–‰
    private void OnDisable()
    {
        Debug.Log("OnDisaable ì‹¤í–‰ ë‚˜ë„ ë”± í•œë²ˆë§Œ ë‚˜ì˜¬êº¼ì•¼");
    }

    //ì–˜ë„ ë”± í•œë²ˆ ì‹¤í–‰
    private void OnDestroy()
    {
        Debug.Log("onDestroy!!!! ë‹¤ ë¶€ìˆ´ë²„ë ·!! ë”± í•œë²ˆ ë‚´ì†ì•ˆì— ëª¨ë“ ê²ƒì´ ì†Œë©¸ë ì§€ë‹ˆ!!! ğŸ˜†");
    }
}
